<?php

declare(strict_types=1);

namespace NfseNacional\Models\Enums;

/**
 * Enum para tipo de evento da NFS-e
 */
enum TipoEvento: string
{
    case CANCELAMENTO = 'CANCELAMENTO';
    case SOLICITACAO_CANCELAMENTO_ANALISE_FISCAL = 'SOLICITACAO_CANCELAMENTO_ANALISE_FISCAL';
    case CANCELAMENTO_POR_SUBSTITUICAO = 'CANCELAMENTO_POR_SUBSTITUICAO';
    case CANCELAMENTO_DEFERIDO_ANALISE_FISCAL = 'CANCELAMENTO_DEFERIDO_ANALISE_FISCAL';
    case CANCELAMENTO_INDEFERIDO_ANALISE_FISCAL = 'CANCELAMENTO_INDEFERIDO_ANALISE_FISCAL';
    case CONFIRMACAO_PRESTADOR = 'CONFIRMACAO_PRESTADOR';
    case REJEICAO_PRESTADOR = 'REJEICAO_PRESTADOR';
    case CONFIRMACAO_TOMADOR = 'CONFIRMACAO_TOMADOR';
    case REJEICAO_TOMADOR = 'REJEICAO_TOMADOR';
    case CONFIRMACAO_INTERMEDIARIO = 'CONFIRMACAO_INTERMEDIARIO';
    case REJEICAO_INTERMEDIARIO = 'REJEICAO_INTERMEDIARIO';
    case CONFIRMACAO_TACITA = 'CONFIRMACAO_TACITA';
    case ANULACAO_REJEICAO = 'ANULACAO_REJEICAO';
    case CANCELAMENTO_POR_OFICIO = 'CANCELAMENTO_POR_OFICIO';
    case BLOQUEIO_POR_OFICIO = 'BLOQUEIO_POR_OFICIO';
    case DESBLOQUEIO_POR_OFICIO = 'DESBLOQUEIO_POR_OFICIO';
    case INCLUSAO_NFSE_DAN = 'INCLUSAO_NFSE_DAN';
    case TRIBUTOS_NFSE_RECOLHIDOS = 'TRIBUTOS_NFSE_RECOLHIDOS';
}

